version: '3.8'

services:
  postgres:
    image: postgres:15.4-alpine3.18
    container_name: postgres_db_reservations
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: SA
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: